#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Write CUPS PPDs for Rongta 203 dpi label printers.

PPDs in this directory are generated by this script. Media dimensions are
inch and millimetre conversions (72 points per inch).
"""

import argparse
import difflib
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent

SIZES = [
    ("4x6in", "4 x 6 in", 288, 432),
    ("4x4in", "4 x 4 in", 288, 288),
    ("4x3in", "4 x 3 in", 288, 216),
    ("4x2in", "4 x 2 in", 288, 144),
    ("4x1in", "4 x 1 in", 288, 72),
    ("4x5in", "4 x 5 in", 288, 360),
    ("4x6.5in", "4 x 6.5 in", 288, 468),
    ("4x13in", "4 x 13 in", 288, 936),
    ("3x3in", "3 x 3 in", 216, 216),
    ("3x2in", "3 x 2 in", 216, 144),
    ("3x1.25in", "3 x 1.25 in", 216, 90),
    ("3x1in", "3 x 1 in", 216, 72),
    ("2.25x1.25in", "2.25 x 1.25 in", 162, 90),
    ("2x1in", "2 x 1 in", 144, 72),
    ("100x150mm", "100 x 150 mm", 283, 425),
]

DEFAULT_SIZE = "4x6in"

MODELS = [
    {
        "file": "Rongta_RP420_ZPL_203dpi.ppd",
        "pc": "RT420Z.PPD",
        "model": "Rongta RP420",
        "short": "Rongta RP420 ZPL",
        "nick": "Rongta RP420 ZPL 203dpi",
        "product": "(Rongta RP420)",
        "lang": "zpl",
    },
    {
        "file": "Rongta_RP421A_ZPL_203dpi.ppd",
        "pc": "RT421A.PPD",
        "model": "Rongta RP421A",
        "short": "Rongta RP421A ZPL",
        "nick": "Rongta RP421A ZPL 203dpi",
        "product": "(Rongta RP421A)",
        "lang": "zpl",
    },
    {
        "file": "Rongta_RP425_ZPL_203dpi.ppd",
        "pc": "RT425Z.PPD",
        "model": "Rongta RP425",
        "short": "Rongta RP425 ZPL",
        "nick": "Rongta RP425 ZPL 203dpi",
        "product": "(Rongta RP425)",
        "lang": "zpl",
    },
    {
        "file": "Rongta_RP422_TSPL_203dpi.ppd",
        "pc": "RT422T.PPD",
        "model": "Rongta RP422",
        "short": "Rongta RP422 TSPL",
        "nick": "Rongta RP422 TSPL 203dpi",
        "product": "(Rongta RP422)",
        "lang": "tspl",
    },
    {
        "file": "Rongta_ZPL_203dpi.ppd",
        "pc": "RTZPL.PPD",
        "model": "Rongta ZPL 203dpi",
        "short": "Rongta ZPL 203dpi",
        "nick": "Rongta ZPL 203dpi",
        "product": "(Rongta ZPL 203dpi)",
        "lang": "zpl",
    },
    {
        "file": "Rongta_TSPL_203dpi.ppd",
        "pc": "RTTSPL.PPD",
        "model": "Rongta TSPL 203dpi",
        "short": "Rongta TSPL 203dpi",
        "nick": "Rongta TSPL 203dpi",
        "product": "(Rongta TSPL 203dpi)",
        "lang": "tspl",
    },
]


def page_code(width, height):
    return f"<</PageSize[{width} {height}]/ImagingBBox null>>setpagedevice"


def size_code(value):
    for key, _label, width, height in SIZES:
        if key == value:
            return page_code(width, height)
    raise KeyError(value)


def choice(keyword, value, label, code=""):
    return f'*{keyword} {value}/{label}: "{code}"\n'


def pickone(lines, keyword, label, default, choices, code_for=None):
    lines.append(f"*OpenUI *{keyword}/{label}: PickOne\n")
    lines.append(f"*Default{keyword}: {default}\n")
    for value, text in choices:
        code = "" if code_for is None else code_for(value)
        lines.append(choice(keyword, value, text, code))
    lines.append(f"*CloseUI: *{keyword}\n\n")


def render(model):
    filt = "rastertozpl-rt" if model["lang"] == "zpl" else "rastertotspl-rt"
    lines = []
    a = lines.append
    a('*PPD-Adobe: "4.3"\n')
    a('*% Rongta 203 dpi label printer. Generated by ppd/gen_ppds.py\n')
    a('*% for the rastertozpl-rt / rastertotspl-rt filters.\n')
    a('*% SPDX-License-Identifier: GPL-3.0-or-later\n')
    a('*% Copyright (C) 2026 blankspeaker (x.com/blankspeaker) and Grok Bot (x.ai/bot)\n')
    a('*FormatVersion: "4.3"\n')
    a('*FileVersion: "1.0"\n')
    a("*LanguageVersion: English\n")
    a("*LanguageEncoding: ISOLatin1\n")
    a(f'*PCFileName: "{model["pc"]}"\n')
    a('*Manufacturer: "Rongta"\n')
    a(f'*Product: "{model["product"]}"\n')
    a(f'*ModelName: "{model["model"]}"\n')
    a(f'*ShortNickName: "{model["short"]}"\n')
    a(f'*NickName: "{model["nick"]}"\n')
    a('*PSVersion: "(3010.000) 0"\n')
    a('*LanguageLevel: "3"\n')
    a("*ColorDevice: False\n")
    a("*DefaultColorSpace: Gray\n")
    a("*FileSystem: False\n")
    a('*Throughput: "4"\n')
    a("*LandscapeOrientation: Plus90\n")
    a("*TTRasterizer: Type42\n")
    a("*cupsVersion: 2.0\n")
    a("*cupsModelNumber: 203\n")
    a("*cupsManualCopies: True\n")
    a(f'*cupsFilter: "application/vnd.cups-raster 100 {filt}"\n')
    a("*HWMargins: 0 0 0 0\n")
    a('*VariablePaperSize: True\n')
    a('*MaxMediaWidth: "324"\n')
    a('*MaxMediaHeight: "1440"\n')
    a("*ParamCustomPageSize Width: 1 points 72 324\n")
    a("*ParamCustomPageSize Height: 2 points 36 1440\n")
    a("*ParamCustomPageSize WidthOffset: 3 points 0 0\n")
    a("*ParamCustomPageSize HeightOffset: 4 points 0 0\n")
    a("*ParamCustomPageSize Orientation: 5 int 0 0\n")
    a('*CustomPageSize True: "pop pop pop <</PageSize[5 -2 roll]/ImagingBBox null>>setpagedevice"\n')
    a("\n*OpenGroup: General/General\n\n")

    a(f"*DefaultPageSize: {DEFAULT_SIZE}\n")
    a(f"*DefaultPageRegion: {DEFAULT_SIZE}\n")
    a(f"*DefaultImageableArea: {DEFAULT_SIZE}\n")
    a(f"*DefaultPaperDimension: {DEFAULT_SIZE}\n\n")

    pickone(
        lines,
        "PageSize",
        "Media Size",
        DEFAULT_SIZE,
        [(k, lab) for k, lab, _w, _h in SIZES],
        code_for=size_code,
    )
    pickone(
        lines,
        "PageRegion",
        "Media Region",
        DEFAULT_SIZE,
        [(k, lab) for k, lab, _w, _h in SIZES],
        code_for=size_code,
    )

    for key, w, h, lab in (
        (s[0], s[2], s[3], s[1]) for s in SIZES
    ):
        a(f'*ImageableArea {key}/{lab}: "0 0 {w} {h}"\n')
    a("\n")
    for key, w, h, lab in (
        (s[0], s[2], s[3], s[1]) for s in SIZES
    ):
        a(f'*PaperDimension {key}/{lab}: "{w} {h}"\n')
    a("\n")

    res = "<</HWResolution[203 203]/cupsBitsPerColor 8/cupsBitsPerPixel 8/cupsColorSpace 3/cupsColorOrder 0>>setpagedevice"
    pickone(lines, "Resolution", "Resolution", "203dpi", [("203dpi", "203 DPI")], code_for=lambda _v: res)
    gray = "<</cupsColorSpace 3/cupsBitsPerColor 8/cupsColorOrder 0>>setpagedevice"
    pickone(lines, "ColorModel", "Color", "Gray", [("Gray", "Grayscale")], code_for=lambda _v: gray)

    pickone(
        lines,
        "MediaType",
        "Media",
        "Gap",
        [("Gap", "Gap"), ("Continuous", "Continuous"), ("BlackMark", "Black mark")],
    )
    pickone(
        lines,
        "PrintSpeed",
        "Print Speed",
        "5",
        [(str(n), f"{n} in/s") for n in (2, 3, 4, 5, 6)],
    )
    pickone(
        lines,
        "Darkness",
        "Darkness",
        "7",
        [(str(n), str(n)) for n in range(16)],
    )
    pickone(
        lines,
        "rtDither",
        "Dither",
        "Threshold",
        [
            ("Threshold", "Threshold"),
            ("FloydSteinberg", "Floyd-Steinberg"),
            ("Bayer", "Ordered Bayer"),
            ("Clustered", "Clustered dot"),
        ],
    )
    home = [-40, -20, -10, 0, 10, 20, 30, 40, 60, 80]
    pickone(
        lines,
        "rtLabelHomeX",
        "Horizontal Offset",
        "20",
        [(str(n), f"{n} dots") for n in home],
    )
    top = [-120, -80, -40, -20, -10, 0, 10, 20, 40, 80, 120]
    pickone(
        lines,
        "rtLabelTop",
        "Vertical Offset",
        "-20",
        [(str(n), f"{n} dots") for n in top],
    )
    pickone(
        lines,
        "rtGapMm",
        "Gap or Mark",
        "2",
        [(str(n), f"{n} mm") for n in (0, 2, 3, 4)],
    )
    pickone(
        lines,
        "rtInvert",
        "Invert",
        "False",
        [("False", "Off"), ("True", "On")],
    )
    if model["lang"] == "zpl":
        pickone(
            lines,
            "rtGfa",
            "Graphic Data",
            "Z64",
            [("Z64", "Z64 compressed"), ("Hex", "ASCII hex")],
        )
    # Dots at 203 dpi. ZPL defaults are the RP425 full-bleed calibration
    # (1 mm left, 1 mm right, 4 mm top, 0 mm bottom). TSPL stays at 0.
    inset = (8, 8, 32, 0) if model["lang"] == "zpl" else (0, 0, 0, 0)
    inset_dots = [0, 4, 8, 12, 16, 24, 32, 40, 48, 64, 80]
    for key, label, default in (
        ("rtInsetLeft", "Inset Left", inset[0]),
        ("rtInsetRight", "Inset Right", inset[1]),
        ("rtInsetTop", "Inset Top", inset[2]),
        ("rtInsetBottom", "Inset Bottom", inset[3]),
    ):
        pickone(
            lines,
            key,
            label,
            str(default),
            [(str(n), f"{n} dots") for n in inset_dots],
        )
    a("*CloseGroup: General\n")
    a('*% End of PPD\n')
    return "".join(lines)


def write_all(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for model in MODELS:
        (directory / model["file"]).write_text(render(model), encoding="utf-8")


def check(directory: Path) -> int:
    failed = 0
    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp)
        write_all(fresh)
        for model in MODELS:
            name = model["file"]
            got = (fresh / name).read_text(encoding="utf-8")
            path = directory / name
            if not path.is_file():
                print(f"missing {path}", file=sys.stderr)
                failed += 1
                continue
            have = path.read_text(encoding="utf-8")
            if have != got:
                print(f"PPD drift: {name}", file=sys.stderr)
                diff = difflib.unified_diff(
                    have.splitlines(True), got.splitlines(True), fromfile=name, tofile=name + ".gen"
                )
                sys.stderr.writelines(list(diff)[:80])
                failed += 1
    return failed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare with files already in ppd/")
    parser.add_argument("--out", type=Path, default=ROOT)
    args = parser.parse_args()
    if args.check:
        return 1 if check(args.out) else 0
    write_all(args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
